// Copyright 2017 Citra Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#pragma once

#include <array>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <span>
#include <boost/serialization/vector.hpp>
#include "common/common_types.h"

namespace Service {
namespace HID {
struct AccelerometerDataEntry;
struct GyroscopeDataEntry;
struct PadState;
struct TouchDataEntry;
} // namespace HID
namespace IR {
struct ExtraHIDResponse;
union PadState;
} // namespace IR
} // namespace Service

namespace Core {

class System;
struct CTMHeader;
struct ControllerState;

class Movie {
public:
    enum class PlayMode : u32 {
        None,
        Recording,
        Playing,
        MovieFinished,
    };

    enum class ValidationResult : u32 {
        OK,
        RevisionDismatch,
        InputCountDismatch,
        Invalid,
    };

    explicit Movie(Core::System& system);
    ~Movie();

    void SetPlaybackCompletionCallback(std::function<void()> completion_callback);
    void StartPlayback(const std::string& movie_file);
    void StartRecording(const std::string& movie_file, const std::string& author);

    /**
     * Sets the read-only status.
     * When true, movies will be opened in read-only mode. Loading a state will resume playback
     * from that state.
     * When false, movies will be opened in read/write mode. Loading a state will start recording
     * from that state (rerecording). To start rerecording without loading a state, one can save
     * and then immediately load while in R/W.
     *
     * The default is true.
     */
    void SetReadOnly(bool read_only);

    /// Prepare to override the clock before playing back movies
    void PrepareForPlayback(const std::string& movie_file);

    /// Prepare to override the clock before recording movies
    void PrepareForRecording();

    ValidationResult ValidateMovie(const std::string& movie_file) const;

    /// Get the init time that would override the one in the settings
    u64 GetOverrideInitTime() const;

    /// Get the base system ticks value that would override the one generated by core timing
    s64 GetOverrideBaseTicks() const;

    struct MovieMetadata {
        u64 program_id;
        std::string author;
        u32 rerecord_count;
        u64 input_count;
    };
    MovieMetadata GetMovieMetadata(const std::string& movie_file) const;

    /// Get the current movie's unique ID. Used to provide separate savestate slots for movies.
    u64 GetCurrentMovieID() const {
        return id;
    }

    void Shutdown();

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandlePadAndCircleStatus(Service::HID::PadState& pad_state, s16& circle_pad_x,
                                  s16& circle_pad_y);

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandleTouchStatus(Service::HID::TouchDataEntry& touch_data);

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandleAccelerometerStatus(Service::HID::AccelerometerDataEntry& accelerometer_data);

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandleGyroscopeStatus(Service::HID::GyroscopeDataEntry& gyroscope_data);

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandleIrRst(Service::IR::PadState& pad_state, s16& c_stick_x, s16& c_stick_y);

    /**
     * When recording: Takes a copy of the given input states so they can be used for playback
     * When playing: Replaces the given input states with the ones stored in the playback file
     */
    void HandleExtraHidResponse(Service::IR::ExtraHIDResponse& extra_hid_response);
    PlayMode GetPlayMode() const;

    u64 GetCurrentInputIndex() const;
    u64 GetTotalInputCount() const;

    /**
     * Saves the movie immediately, in its current state.
     * This is called in Shutdown.
     */
    void SaveMovie();

    /// Sets the file the movie is saved to
    void SetMovieFile(const std::string& movie_file) {
        record_movie_file = movie_file;
    }

    // ---------------------------------------------------------------------------------------------
    // TAS editor (TAStudio-like piano roll)
    //
    // While enabled, the inputs of the movie are also kept per frame (a frame being one vblank
    // period of emulated time). While recording, frames that are already in the table are replayed
    // from it (edited values, or the exact inputs captured when the frame was first emulated), and
    // frames past its end are captured from the live input. Everything that reaches the game is
    // still recorded into the movie as usual, so saved movies play back on any build.
    //
    // Savestates of the emulator ("greenzone") are kept in memory every few frames, so that the
    // emulator can go back to any earlier frame by loading the closest state and emulating forward.
    // ---------------------------------------------------------------------------------------------

    /// Inputs of one frame as shown and edited in the TAS editor
    struct TasFrame {
        /// Pad buttons, using the bits of the movie file: 0 A, 1 B, 2 Select, 3 Start, 4 Right,
        /// 5 Left, 6 Up, 7 Down, 8 R, 9 L, 10 X, 11 Y
        u16 buttons = 0;
        s16 circle_x = 0;
        s16 circle_y = 0;
        bool touch = false;
        u16 touch_x = 0;
        u16 touch_y = 0;
        bool zl = false;
        bool zr = false;
        /// C-stick in IR:RST units (-0x9C to 0x9C)
        s16 c_stick_x = 0;
        s16 c_stick_y = 0;
        std::array<s16, 3> accel{};
        std::array<s16, 3> gyro{};

        bool operator==(const TasFrame&) const = default;
    };

    void EnableTasEditor(bool enable);
    bool IsTasEditorEnabled() const;

    /// Number of frames in the table
    std::size_t TasFrameCount() const;
    /// Frames before this one were emulated before the TAS editor was enabled and are not known
    u64 TasFirstFrame() const;
    TasFrame TasGetFrame(std::size_t index) const;
    std::vector<TasFrame> TasGetFrames(std::size_t index, std::size_t count) const;
    /// Whether a frame has values set in the editor (instead of the exact captured inputs)
    bool TasIsFrameEdited(std::size_t index) const;
    /// Whether the frame has been emulated and captured, or was created in the editor
    bool TasIsFrameKnown(std::size_t index) const;
    void TasSetFrame(std::size_t index, const TasFrame& frame);
    void TasInsertFrames(std::size_t index, const std::vector<TasFrame>& frames);
    void TasDeleteFrames(std::size_t index, std::size_t count);

    /// Frame the emulator is at, i.e. the next frame to be emulated
    u64 TasCurrentFrame() const;
    /// Whether a savestate of the given frame is kept
    bool TasHasState(u64 frame) const;
    std::size_t TasStateCount() const;
    std::size_t TasStateMemoryUsage() const;
    void TasSetStateInterval(u32 frames);
    void TasSetStateCapacity(u32 states);
    /// Asks the emulator to go to the given frame, loading a savestate if needed. The emulator
    /// pauses (frame advancing) once it reaches the frame.
    void TasRequestSeek(u64 frame);
    bool TasIsSeeking() const;
    /// While set, frames in the table are recorded from the live input instead of replayed
    void TasSetOverwrite(bool overwrite);

    // Used by the core (emulator thread)
    std::optional<u64> TasTakeSeekRequest();
    /// Returns the closest savestate at or before the frame
    struct TasStateRef {
        u64 frame;
        std::vector<u8> state;
    };
    std::optional<TasStateRef> TasFindState(u64 frame) const;
    /// Restores the replay position that was current when the state of the frame was taken
    void TasRestoreStatePosition(u64 frame);
    bool TasWantsState() const;
    void TasStoreState(std::vector<u8> state);
    void TasSetSeekTarget(std::optional<u64> frame);
    /// Called at every vblank. Returns true if a seek reached its target.
    bool TasOnVBlank();
    u64 TasFrameNow() const;

private:
    void CheckInputEnd();

    template <typename... Targs>
    void Handle(Targs&... Fargs);

    void Play(Service::HID::PadState& pad_state, s16& circle_pad_x, s16& circle_pad_y);
    void Play(Service::HID::TouchDataEntry& touch_data);
    void Play(Service::HID::AccelerometerDataEntry& accelerometer_data);
    void Play(Service::HID::GyroscopeDataEntry& gyroscope_data);
    void Play(Service::IR::PadState& pad_state, s16& c_stick_x, s16& c_stick_y);
    void Play(Service::IR::ExtraHIDResponse& extra_hid_response);

    void Record(const ControllerState& controller_state);
    void Record(const Service::HID::PadState& pad_state, const s16& circle_pad_x,
                const s16& circle_pad_y);
    void Record(const Service::HID::TouchDataEntry& touch_data);
    void Record(const Service::HID::AccelerometerDataEntry& accelerometer_data);
    void Record(const Service::HID::GyroscopeDataEntry& gyroscope_data);
    void Record(const Service::IR::PadState& pad_state, const s16& c_stick_x, const s16& c_stick_y);
    void Record(const Service::IR::ExtraHIDResponse& extra_hid_response);

    ValidationResult ValidateHeader(const CTMHeader& header) const;
    ValidationResult ValidateInput(std::span<const u8> input, u64 expected_count) const;

private:
    struct TasData;
    ControllerState TasResolve(const ControllerState& live);
    void TasInvalidateStatesFrom(std::size_t frame);

    std::unique_ptr<TasData> tas;
    /// Ticks at the start of the movie, used when the movie has no base ticks
    s64 tas_origin_ticks = 0;
    mutable std::mutex tas_mutex;

    Core::System& system;
    PlayMode play_mode;

    std::string record_movie_file;
    std::string record_movie_author;

    u64 init_time;       // Clock init time override for RNG consistency
    s64 base_ticks = -1; // Core timing base system ticks override for RNG consistency

    std::vector<u8> recorded_input;
    std::size_t current_byte = 0;
    u64 current_input = 0;
    // Total input count of the current movie being played. Not used for recording.
    u64 total_input = 0;

    u64 id = 0; // ID of the current movie loaded
    u64 program_id = 0;
    u32 rerecord_count = 1;
    bool read_only = true;

    std::function<void()> playback_completion_callback = [] {};

    template <class Archive>
    void serialize(Archive& ar, const unsigned int file_version);
    friend class boost::serialization::access;
};
} // namespace Core

BOOST_CLASS_VERSION(Core::Movie, 1)
